server {
    listen 8420;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|json)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
